/*
 * generated by Fujaba - CodeGen2
 */

package org.qsari.effectopedia.core.containers;

import org.qsari.effectopedia.base.EffectopediaObject;
import org.qsari.effectopedia.base.EffectopediaObjects;
import org.qsari.effectopedia.base.ids.ReferenceIDs;
import org.qsari.effectopedia.core.objects.Reference;
import org.qsari.effectopedia.data.DataSource;

public class References extends EffectopediaObjects<Reference>
	{
		/**
	 * 
	 */
		private static final long	serialVersionUID	= 1L;
	
		public boolean addNew(EffectopediaObject parent,DataSource dataSource, Class<Reference> objectClass)
			{
				Reference r = new Reference(parent,dataSource);
				Reference old = put(r.getID(), r);
				return (old == null) || (old == r);
			}
		
		public Reference[] get()
			{
				return values().toArray(new Reference[values().size()]);
			}
		
		public interface Referable
			{
				public ReferenceIDs<Reference> getReferenceIDs();
			}
		
		public String toString()
			{
				return "references";
			}
		
		public static final Class<?>	objectsClass	= Reference.class;
	}
